### ISSUE TITLE
Me again, sorry. It gets a very small way into comments and throws a huge ugly error.

### ISSUE THREAD

**Issue by adrienne** [danlmarmot/livejournal-export#4]
Any ideas? Here's the error:
```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\response.py", line 535, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\response.py", line 298, in _error_catcher
    yield
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\response.py", line 590, in read_chunked
    self._update_chunk_length()
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\response.py", line 539, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\requests\models.py", line 703, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\response.py", line 428, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\response.py", line 618, in read_chunked
    self._original_response.close()
  File "C:\Python36\lib\contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python36\lib\site-packages\requests\packages\urllib3\response.py", line 316, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0
 bytes read))
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\AdrienneTemp\livejournal-export-master\export.py", line 752, in <module>
    main()
  File "C:\AdrienneTemp\livejournal-export-master\export.py", line 78, in main
    download_comments(export_dirs['comments_xml'], export_dirs['lj_user'])
  File "C:\AdrienneTemp\livejournal-export-master\export.py", line 235, in download_comments
    start_id, comments = get_more_comments(start_id + 1, users, comments_xml_dir)
  File "C:\AdrienneTemp\livejournal-export-master\export.py", line 670, in get_more_comments
    xml = fetch_xml({'get': 'comment_body', 'startid': start_id})
  File "C:\AdrienneTemp\livejournal-export-master\export.py", line 620, in fetch_xml
    cookies=get_cookies()
  File "C:\Python36\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python36\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 641, in send
    r.content
  File "C:\Python36\lib\site-packages\requests\models.py", line 781, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Python36\lib\site-packages\requests\models.py", line 706, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes rea
d))
```

**Comment by adrienne** [comment]
Never mind, i fixed my own problem! See pull request #5!
